# Generated by Django 4.1.1 on 2022-10-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HelioDist', models.FloatField(default=float("nan"))),
                ('HGILat', models.FloatField(default=float("nan"))),
                ('HGILon', models.FloatField(default=float("nan"))),
                ('BR', models.FloatField(default=float("nan"))),
                ('BT', models.FloatField(default=float("nan"))),
                ('BN', models.FloatField(default=float("nan"))),
                ('B', models.FloatField(default=float("nan"))),
                ('VR', models.FloatField(default=float("nan"))),
                ('VT', models.FloatField(default=float("nan"))),
                ('VN', models.FloatField(default=float("nan"))),
                ('Speed', models.FloatField(default=float("nan"))),
                ('FlowEle', models.FloatField(default=float("nan"))),
                ('FlowAng', models.FloatField(default=float("nan"))),
                ('Density', models.FloatField(default=float("nan"))),
                ('Temp', models.FloatField(default=float("nan"))),
                ('isBNaN', models.FloatField(default=float("nan"))),
                ('isSpeedNaN', models.FloatField(default=float("nan"))),
            ],
        ),
    ]
