# Generated by Django 4.1.1 on 2022-10-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mergedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='B',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='BN',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='BR',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='BT',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='Density',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='FlowAng',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='FlowEle',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='HGILat',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='HGILon',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='HelioDist',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='Speed',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='Temp',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='VN',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='VR',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='VT',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='isBNaN',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='data',
            name='isSpeedNaN',
            field=models.FloatField(default=float("nan")),
        ),
    ]
