# Generated by Django 4.1.1 on 2022-10-02 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mergedata', '0005_alter_data_b_alter_data_bn_alter_data_br_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Time',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='B',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BR',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BT',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Density',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='FlowAng',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='FlowEle',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HGILat',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HGILon',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HelioDist',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Speed',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Temp',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='VN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='VR',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='VT',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='isBNaN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='isSpeedNaN',
            field=models.FloatField(default=float("nan"), null=True),
        ),
    ]
