# Generated by Django 4.1.1 on 2022-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folder', models.CharField(max_length=200)),
                ('PNG', models.CharField(max_length=200)),
                ('Time', models.CharField(max_length=200)),
            ],
        ),
    ]
